### ISSUE TITLE
Missing BumperState.h

### ISSUE THREAD

**Issue by JohanneLun** [thentnucyborg/CyborgRobot#1]
when running catkin_make for the first few times, or after removing the /devel and /build folders you get this error message:
"/home/cyborg/catkin_ws/src/rosaria_client/src/print_state.cpp:7:33: fatal error: rosaria/BumperState.h: No such file or directory"

It appears to be some dependecy problem. It is solved/dissapears after you run a few catkin_make commands. 
Have had a similar problem with another project and the issue was solved there by specifying some dependecies in the file CMakeList.txt within the node making trouble. 
Have not found the right change yet.

**Comment by paytience** [comment]
There is definitely a build order problem. I built only the rosarnl package using 
<catkin_make -DCATKIN_WHITELIST_PACKAGES="rosarnl"> several times and it would randomly build to 100%. 

The difference between a successful build and an unsuccessful one was that some python and c++ code would be generated **before** the generation of the 'rosarnl_node.cpp' node, which is the source of the error. 

This was solved without any errors by running <catkin_make_isolated> instead of <catkin_make>.
It ensures that one package is built at a time depending on build order. 
Updated the setup script to use _isolated.

**Comment by paytience** [comment]
Changed back to catkin_make, catkin_make isolated does not generate CMakeLists.txt files for newly-built packages so this choice of workspace builder could become troublesome later on. 
Instead, catkin_make bugs were fixed. 
Error 1: 
No such file or directory - rosaria_client print state, bumperstate.h:
Added *add_dependencies(print_state ${catkin_EXPORTED_TARGETS})* to CMakeLists.txt in rosaria_client
https://answers.ros.org/question/206257/catkin-use-ros-message-from-another-package/

Error 2:
rosarnl/BatteryStatus.h: No such file or directory
Added *add_dependencies(rosarnl_node rosarnl_gencpp)* to CMakeLists.txt in ros-arnl.

**Comment by reedhedges** [comment]
Would it be better for bumper_state to be in a separate rosaria_msgs package?  Or to replace bumper_state with something more standard/generic? I think it's the only rosaria specific message type.
